name: M Centers 8.0 x64/x86 Builds

on:
  workflow_dispatch:

jobs:
  x64:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore Packages
      run: nuget restore "M Centers 8.0.sln"

    - name: Build M Centers (x64)
      run: msbuild MCenters/MCenters.csproj /p:Configuration=Release /p:Platform=x64 /t:Rebuild
      
    - name: Publish M Centers (x64)
      uses: actions/upload-artifact@v4
      with:
        name: M-Centers-8.0-Release x64
        path: D:\a\M-Centers-8.0\M-Centers-8.0\MCenters\bin\x64\Release\
  x86:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore Packages
      run: nuget restore "M Centers 8.0.sln"

    - name: Build M Centers (x86)
      run: msbuild MCenters/MCenters.csproj /p:Configuration=Release /p:Platform=x86 /t:Rebuild

    - name: Publish M Centers (x86)
      uses: actions/upload-artifact@v4
      with:
        name: M-Centers-8.0-Release x86
        path: D:\a\M-Centers-8.0\M-Centers-8.0\MCenters\bin\x86\Release\
