name: Build WPF Application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-x64:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Framework SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '4.7.2'

    - name: Restore NuGet Packages
      run: nuget restore MCenters.csproj

    - name: Build WPF Application (x64)
      run: msbuild MCenters.csproj /p:Configuration=Release /p:Platform=x64 /t:Rebuild

    - name: Publish Artifact (x64)
      uses: actions/upload-artifact@v2
      with:
        name: wpf-app-x64
        path: Releases/x64/executable

  build-x86:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Framework SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '4.7.2'

    - name: Restore NuGet Packages
      run: nuget restore MCenters.csproj

    - name: Build WPF Application (x86)
      run: msbuild MCenters.csproj /p:Configuration=Release /p:Platform=x86 /t:Rebuild

    - name: Publish Artifact (x86)
      uses: actions/upload-artifact@v2
      with:
        name: wpf-app-x86
        path: Releases/x86/executable
