name: reMCenters x64/x86 Builds

on:
  push:

jobs:
  x64:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore Packages
      run: nuget restore "reMCenters.sln"

    - name: Build reMCenters (x64)
      run: msbuild reMCenters/reMCenters.csproj /p:Configuration=Release /p:Platform=x64 /t:Rebuild
      
    - name: Publish reMCenters (x64)
      uses: actions/upload-artifact@v4
      with:
        name: reMCenters-Release_x64
        path: D:\a\reMCenters\reMCenters\reMCenters\bin\x64\Release\
  x86:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore Packages
      run: nuget restore "reMCenters.sln"

    - name: Build reMCenters (x86)
      run: msbuild reMCenters/reMCenters.csproj /p:Configuration=Release /p:Platform=x86 /t:Rebuild

    - name: Publish reMCenters (x86)
      uses: actions/upload-artifact@v4
      with:
        name: reMCenters-Release_x86
        path: D:\a\reMCenters\reMCenters\reMCenters\bin\x86\Release\
